"""
Gemini prompt for Sector Analysis summary generation.
"""
from schemas.analysis_schemas import PeerData


def build_sector_summary_prompt(
    ticker: str,
    company_name: str,
    sector: str,
    target_metrics: dict,
    peers: list[PeerData],
) -> str:
    peer_rows = ""
    for p in peers:
        peer_rows += (
            f"  - {p.name} ({p.ticker}): P/E={p.pe_ratio}, "
            f"MarketCap={p.market_cap}, ROE={p.roe}, "
            f"RevenueGrowth={p.revenue_growth}\n"
        )

    return f"""You are a sector research analyst covering Indian equities.

Analyse the competitive position of {company_name} ({ticker}) in the {sector} sector.

TARGET COMPANY METRICS:
{target_metrics}

PEER COMPANIES:
{peer_rows or "  No peer data available."}

Respond in this EXACT JSON format (no markdown, no preamble):
{{
  "sector_strength": "<Strong | Average | Weak>",
  "relative_position": "<Leader | Average | Laggard>",
  "sector_pe_avg": <float or null>,
  "sector_growth_avg": <float or null>,
  "peer_comparison": [
    {{
      "ticker": "<str>",
      "name": "<str>",
      "vs_target": "<Better | Similar | Worse>",
      "key_difference": "<1 sentence>"
    }}
  ]
}}

Return ONLY valid JSON.
"""


def build_market_brief_prompt(
    nifty_data: dict,
    sensex_data: dict,
    top_gainers: list[dict],
    top_losers: list[dict],
    market_news: list[dict],
) -> str:
    gainers_str = "\n".join(
        f"  - {g.get('symbol','?')}: +{g.get('change_pct',0):.2f}%"
        for g in top_gainers[:5]
    )
    losers_str = "\n".join(
        f"  - {l.get('symbol','?')}: {l.get('change_pct',0):.2f}%"
        for l in top_losers[:5]
    )
    news_str = "\n".join(f"  - {n.get('title','')}" for n in market_news[:10])

    return f"""You are a senior Indian market strategist writing the morning market brief.

MARKET DATA:
NIFTY 50: {nifty_data}
SENSEX: {sensex_data}

TOP GAINERS:
{gainers_str or "  Data unavailable"}

TOP LOSERS:
{losers_str or "  Data unavailable"}

MARKET NEWS:
{news_str or "  No news available"}

Write a professional morning market brief in Markdown covering:

# 🇮🇳 Indian Market Brief — [Today's Date]

## Market Overview
[NIFTY and SENSEX performance, overall market tone]

## Key Movers
[Top gainers and losers with context]

## Sector Highlights
[Which sectors are outperforming/underperforming]

## Key News & Catalysts
[Most impactful news affecting markets today]

## What to Watch
[3 things investors should monitor today]

---
*Generated by Multi-Agent Indian Stock Research Platform*

Keep it concise, factual, and actionable. Return ONLY the Markdown.
"""